name: Generate documentation using Granite

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TECHDOCS_S3_BUCKET_NAME: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}`
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-north-1'
      ENTITY_NAMESPACE: 'eks-infra'
      ENTITY_KIND: 'Component'
      ENTITY_NAME: 'eks-cluster'
    steps:
      - uses: actions/checkout@v4

      - name: Checkout external repository
        uses: actions/checkout@v3
        with:
          repository: whiteboard-organization/watsonX-ai.git
          path: watsonX
          ref: hackathon/oa-02
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ibm_watsonx_ai
          pip install ibm_watson_machine_learning
          pip install pandas --upgrade

      - name: Replace placeholders in config file
        env:
          COS_API_KEY: ${{ secrets.COS_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          PROJECT_API_KEY_1: ${{ secrets.PROJECT_API_KEY_1 }}
          PROJECT_API_KEY_2: ${{ secrets.PROJECT_API_KEY_2 }}
        run: |
          envsubst < watsonX/watson/sample-conf.json > watsonX/watson/config.json
          cat watsonX/watson/config.json

      - name: Run Python script
        run: |
          python watsonX/watson/watson.py eks-cluster ${{ secrets.PROJECT_API_KEY_3 }}
          ls /home/runner/work/eks_infra/eks_infra/watsonX/

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose --source-dir /home/runner/work/eks_infra/eks_infra/watsonX

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME --directory /home/runner/work/eks_infra/eks_infra/site
