# This is a basic workflow to help you get started with Actions

name: Generate documentation using Granite

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TECHDOCS_S3_BUCKET_NAME: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-north-1'
      ENTITY_NAMESPACE: 'default'
      ENTITY_KIND: 'Component'
      ENTITY_NAME: 'my-doc-entity'
      # In a Software template, Scaffolder will replace {{cookiecutter.component_id | jsonify}}
      # with the correct entity name. This is same as metadata.name in the entity's catalog-info.yaml
      # ENTITY_NAME: '{{ cookiecutter.component_id | jsonify }}'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          ls .

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Checkout external repository
        uses: actions/checkout@v3
        with:
          repository: whiteboard-organization/watsonX-ai.git
          path: watsonX
          ref: hackathon/rt-01
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ibm_watsonx_ai
          pip install ibm_watson_machine_learning
          pip install pandas --upgrade

      - name: Replace placeholders in config file
        env:
          COS_API_KEY: ${{ secrets.COS_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          PROJECT_API_KEY_1: ${{ secrets.PROJECT_API_KEY_1 }}
          PROJECT_API_KEY_2: ${{ secrets.PROJECT_API_KEY_2 }}
        run: |
          envsubst < watsonX/watson/sample-conf.json > watsonX/watson/config.json
          cat watsonX/watson/config.json

      - name: Run Python script
        run: |
          echo "this ls ."
          ls .
          pwd
          python watsonX/watson/watson.py eks-cluster ${{ secrets.PROJECT_API_KEY_2 }}
          ls /home/runner/work/eks_infra/eks_infra/watsonX/watson/../generated-docs/

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose --source-dir /home/runner/work/eks_infra/eks_infra/watsonX/watson/../generated-docs/

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME --source-dir /home/runner/work/eks_infra/eks_infra/watsonX/watson/../generated-docs/
